# Save the model periodically by monitoring a quantity.
# Look at the above link for more detailed information.
model_checkpoint_best:
  _target_: gabbro.callbacks.checkpoint_callback.CustomModelCheckpoint
  state_key: "Best-checkpoint-callback"
  dirpath: null # directory to save the model file
  filename: best # checkpoint filename
  monitor: "val_acc" # name of the logged metric which determines when model is improving
  verbose: true # verbosity mode
  save_last: null # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: 1 # save k best models (determined by above metric)
  mode: "max" # "max" means higher metric value is better, can be also "min"
  auto_insert_metric_name: false # when True, the checkpoints filenames will contain the metric name
  save_weights_only: false # if True, then only the model’s weights will be saved
  every_n_train_steps: null # number of training steps between checkpoints
  train_time_interval: null # checkpoints are monitored at the specified time interval
  every_n_epochs: null # number of epochs between checkpoints
  save_on_train_epoch_end: false # whether to run checkpointing at the end of the training epoch or the end of validation
