
num_channels_scalar: 10

num_channels_m:
  - 
    - 60
  - 
    - 60
  - 
    - 60
  - 
    - 60
  - 
    - 60
num_channels_2to2: 
  - 35
  - 35
  - 35
  - 35
  - 35
num_channels_m_out:
  - 60
  - 35
num_channels_out: 
  - 60