
datadir: ../data/btW_7_d
task: train
nobj: 60
nobj_avg: 35
batch_size: 128
num_epoch: 35
num_valid: 30000
num_train: -1

stabilizer: so2
method: spurions

drop_rate: 0.025
drop_rate_out: 0.025
weight_decay: 0.005
summarize: False