
num_channels_scalar: 30

num_channels_m:
  - 
    - 186
  - 
    - 186
  - 
    - 186
  - 
    - 186
  - 
    - 186
num_channels_2to2: 
  - 110
  - 110
  - 110
  - 110
  - 110
num_channels_m_out:
  - 186
  - 110
num_channels_out: 
  - 186